repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
          - --no-ensure-ascii
        exclude: package-lock.json
      - id: trailing-whitespace

#  - repo: local
#    hooks:
#      - id: eslint
#        name: ESLint
#        entry: npx eslint
#        language: system
